url=jdbc:postgresql://unihealth-db:5432/uniwa_c2
username=postgres
password=postgres
admin-username=uniwa1_c2
admin-email=uniwa1_c2@unihealth.gr
admin-firstname=uniwa_c2adminfirstname
admin-lastname=uniwa_c2adminlastname
admin-language=el
