# Build
build.version=@project.version@
# Datasource
tenants.location=classpath:db/tenants/local
schema.validation=true
datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
# Liquibase
spring.liquibase.enabled=false
spring.liquibase.changeLog=classpath:/db/changelog/db.changelog-master.xml
# Servlet
server.servlet.context-path=/api
# Authentication
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://unihealth-keycloak:8080/keycloak/realms/unihealth/protocol/openid-connect/certs
unihealth.security.jwt.expected-issuer=http://localhost:4200/keycloak/realms/unihealth
# OpenAPI
springdoc.api-docs.enabled=false
# Keycloak service authentication
keycloak.server-url=http://unihealth-keycloak:8080/keycloak
keycloak.realm-master=master
keycloak.realm-unihealth=unihealth
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin
unihealth.app.jobs.users.deactivate.cron=0 0 0 * * *
unihealth.app.jobs.users.deactivate.inactivity.days=395
unihealth.app.jobs.users.inform.inactivity.days=365
unihealth.app.users.deactivate.reactivated.after.days=21
unihealth.app.users.delete.unverified.after.days=21
unihealth.app.jobs.mail.send.cron=*/5 * * * * *
unihealth.app.jobs.mail.cleanup.cron=0 0 1 ? * SAT
# Mail
spring.mail.max_tries=3
spring.mail.debug=false
spring.mail.polling=true
spring.mail.host=unihealth-mail
spring.mail.port=1025
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.auth=false
spring.mail.from=noreply@unihealth.gr
spring.mail.from-display-name=UNIHEALTH
# spring.mail.username = dev_username
# spring.mail.password = dev_password
unihealth.app.www.url=http://www.unihealth.gr
# RSS FEED
unihealth.app.rss.jobs.refresh.cron=0 0 8 * * *
app.rss.sources[0].name=myfitnesspal
app.rss.sources[0].url=https://blog.myfitnesspal.com/feed/
app.rss.sources[1].name=mayhealthylifestyle
app.rss.sources[1].url=https://mayhealthylifestyle.com/feed/
#Redis
spring.data.redis.host=unihealth-redis
spring.data.redis.port=6379
spring.cache.type=redis
