url=jdbc:postgresql://localhost:5432/uniwa_c1
username=postgres
password=postgres
admin-username=uniwa1_c1
admin-email=uniwa1_c1@unihealth.gr
admin-firstname=uniwa_c1adminfirstname
admin-lastname=uniwa_c1adminlastname
admin-language=el
