export type WellnessPageKey = 'recipes' | 'fitness' | 'mental';
export type WellnessItemKind = 'Recipe' | 'Workout' | 'Mind practice';

export interface WellnessItem {
    id: string;
    title: string;
    kind: WellnessItemKind;
    category: string;
    summary: string;
    detail: string;
    icon: string;
    accentColor: string;
    duration: string;
    level: string;
    metricLabel: string;
    metricValue: string;
    tags: string[];
    highlights: string[];
    steps: string[];
}

export interface WellnessCollection {
    key: WellnessPageKey;
    eyebrow: string;
    title: string;
    description: string;
    featuredLabel: string;
    categories: string[];
    items: WellnessItem[];
}

export const WELLNESS_COLLECTIONS: Record<WellnessPageKey, WellnessCollection> = {
    recipes: {
        key: 'recipes',
        eyebrow: 'Healthy recipes',
        title: 'Simple meals for busy student days',
        description: 'Mock meal ideas designed around realistic prep time, balanced nutrition, and everyday ingredients.',
        featuredLabel: 'Featured meal',
        categories: ['All', 'Breakfast', 'Lunch', 'Dinner', 'Snack'],
        items: [
            {
                id: 'greek-yogurt-bowl',
                title: 'Greek Yogurt Power Bowl',
                kind: 'Recipe',
                category: 'Breakfast',
                summary: 'A high-protein bowl with fruit, oats, seeds, and a practical allergy-aware swap.',
                detail: 'This breakfast is built for quick assembly and steady energy. It combines protein, fiber, and healthy fats without needing cooking equipment.',
                icon: 'breakfast_dining',
                accentColor: '#27764f',
                duration: '7 min',
                level: 'Easy',
                metricLabel: 'Protein',
                metricValue: '24g',
                tags: ['High protein', 'No cook', 'Budget'],
                highlights: ['Greek yogurt or soy yogurt', 'Oats or granola', 'Berries or banana', 'Chia or pumpkin seeds'],
                steps: ['Add yogurt to a bowl.', 'Top with fruit, oats, and seeds.', 'Use cinnamon or honey lightly for flavor.'],
            },
            {
                id: 'lentil-rice-box',
                title: 'Lentil Rice Lunch Box',
                kind: 'Recipe',
                category: 'Lunch',
                summary: 'A filling campus lunch with lentils, rice, vegetables, and lemon dressing.',
                detail: 'Lentils and rice are inexpensive, portable, and satisfying. This mock recipe works well as a batch-prep option for two or three study days.',
                icon: 'lunch_dining',
                accentColor: '#1f6f78',
                duration: '25 min',
                level: 'Easy',
                metricLabel: 'Fiber',
                metricValue: '12g',
                tags: ['Meal prep', 'Plant based', 'Fiber'],
                highlights: ['Cooked lentils', 'Brown rice', 'Cucumber and tomato', 'Olive oil lemon dressing'],
                steps: ['Combine cooked lentils and rice.', 'Add chopped vegetables.', 'Dress with lemon, olive oil, oregano, and pepper.'],
            },
            {
                id: 'salmon-tray',
                title: 'Salmon and Veg Tray',
                kind: 'Recipe',
                category: 'Dinner',
                summary: 'A sheet-pan dinner with vegetables, potatoes, and omega-3 rich protein.',
                detail: 'Tray meals reduce cleanup and help make a complete dinner feel manageable after classes. Swap salmon for tofu or chicken if preferred.',
                icon: 'set_meal',
                accentColor: '#2c62a2',
                duration: '30 min',
                level: 'Moderate',
                metricLabel: 'Serves',
                metricValue: '2',
                tags: ['Omega-3', 'Dinner', 'Tray bake'],
                highlights: ['Salmon fillet', 'Potatoes', 'Zucchini', 'Lemon and herbs'],
                steps: ['Arrange ingredients on a lined tray.', 'Season with lemon, herbs, and olive oil.', 'Bake until cooked through.'],
            },
            {
                id: 'hummus-snack-plate',
                title: 'Hummus Snack Plate',
                kind: 'Recipe',
                category: 'Snack',
                summary: 'A quick snack plate with vegetables, whole-grain crackers, and hummus.',
                detail: 'Snack plates help bridge long class blocks without relying only on sweets or vending-machine food.',
                icon: 'tapas',
                accentColor: '#9d6a18',
                duration: '5 min',
                level: 'Easy',
                metricLabel: 'Prep',
                metricValue: 'No cook',
                tags: ['Snack', 'Portable', 'Vegetables'],
                highlights: ['Hummus', 'Carrot sticks', 'Cucumber', 'Whole-grain crackers'],
                steps: ['Slice vegetables.', 'Add hummus to a small container.', 'Pack crackers separately to keep texture.'],
            },
        ],
    },
    fitness: {
        key: 'fitness',
        eyebrow: 'Fitness plans',
        title: 'Movement plans that fit real schedules',
        description: 'Mock routines for strength, mobility, cardio, and study-break movement without complex equipment.',
        featuredLabel: 'Featured routine',
        categories: ['All', 'Strength', 'Cardio', 'Mobility', 'Study Break'],
        items: [
            {
                id: 'full-body-basics',
                title: 'Full Body Basics',
                kind: 'Workout',
                category: 'Strength',
                summary: 'A beginner strength circuit using bodyweight movements and simple progressions.',
                detail: 'This routine covers squat, push, hinge, pull, and core patterns. It is meant to feel repeatable, not exhausting.',
                icon: 'fitness_center',
                accentColor: '#b95745',
                duration: '28 min',
                level: 'Beginner',
                metricLabel: 'Rounds',
                metricValue: '3',
                tags: ['Strength', 'No gym', 'Beginner'],
                highlights: ['Squats', 'Wall push-ups', 'Hip hinges', 'Dead bug core work'],
                steps: ['Warm up for five minutes.', 'Complete each movement for 8 to 12 reps.', 'Rest 60 seconds between rounds.'],
            },
            {
                id: 'campus-walk',
                title: 'Campus Cardio Walk',
                kind: 'Workout',
                category: 'Cardio',
                summary: 'A brisk walking session that uses campus paths and natural intervals.',
                detail: 'Walking is accessible and easy to scale. This mock session alternates normal pace and brisk pace to support cardiovascular fitness.',
                icon: 'directions_walk',
                accentColor: '#1f6f78',
                duration: '35 min',
                level: 'Easy',
                metricLabel: 'Intervals',
                metricValue: '8',
                tags: ['Walking', 'Heart health', 'Low impact'],
                highlights: ['5-minute warm-up', '2-minute brisk intervals', 'Easy recovery pace', 'Cool down'],
                steps: ['Walk easy for five minutes.', 'Alternate brisk and easy pace.', 'Finish with relaxed walking and stretching.'],
            },
            {
                id: 'desk-mobility',
                title: 'Desk Mobility Reset',
                kind: 'Workout',
                category: 'Mobility',
                summary: 'A short mobility reset for neck, shoulders, hips, and back after screen time.',
                detail: 'Frequent small mobility breaks can reduce stiffness from long study sessions. Movements should feel gentle and controlled.',
                icon: 'accessibility_new',
                accentColor: '#6a5aa8',
                duration: '10 min',
                level: 'Easy',
                metricLabel: 'Moves',
                metricValue: '6',
                tags: ['Mobility', 'Desk', 'Posture'],
                highlights: ['Neck rotations', 'Shoulder rolls', 'Thoracic openers', 'Hip flexor stretch'],
                steps: ['Move slowly through each drill.', 'Hold stretches for 20 to 30 seconds.', 'Stop if pain appears.'],
            },
            {
                id: 'exam-week-mini',
                title: 'Exam Week Mini Session',
                kind: 'Workout',
                category: 'Study Break',
                summary: 'A compact session to raise energy between revision blocks.',
                detail: 'This routine is intentionally short. It helps interrupt sitting time without turning a study day into a full training day.',
                icon: 'timer',
                accentColor: '#2c62a2',
                duration: '8 min',
                level: 'All levels',
                metricLabel: 'Space',
                metricValue: 'Small',
                tags: ['Study break', 'Energy', 'Quick'],
                highlights: ['Marching in place', 'Air squats', 'Arm circles', 'Calf raises'],
                steps: ['Set an eight-minute timer.', 'Cycle through four low-impact movements.', 'Return to studying with water nearby.'],
            },
        ],
    },
    mental: {
        key: 'mental',
        eyebrow: 'Mental wellbeing',
        title: 'Practical tools for calmer study weeks',
        description: 'Mock practices for stress regulation, focus, social connection, and recovery during demanding academic periods.',
        featuredLabel: 'Featured practice',
        categories: ['All', 'Stress', 'Focus', 'Connection', 'Recovery'],
        items: [
            {
                id: 'two-minute-breathing',
                title: 'Two-Minute Breathing Reset',
                kind: 'Mind practice',
                category: 'Stress',
                summary: 'A short paced-breathing practice for moments of acute pressure.',
                detail: 'Paced breathing can help reduce the intensity of stress signals enough to choose a useful next step. It is simple and private.',
                icon: 'self_improvement',
                accentColor: '#2c62a2',
                duration: '2 min',
                level: 'Easy',
                metricLabel: 'Pattern',
                metricValue: '4-6',
                tags: ['Breathing', 'Stress', 'Fast'],
                highlights: ['Inhale four counts', 'Exhale six counts', 'Relax shoulders', 'Repeat gently'],
                steps: ['Sit upright with feet supported.', 'Inhale through the nose for four counts.', 'Exhale slowly for six counts.'],
            },
            {
                id: 'focus-sprint',
                title: 'Focused Study Sprint',
                kind: 'Mind practice',
                category: 'Focus',
                summary: 'A structured sprint that reduces overwhelm by defining one next task.',
                detail: 'Study sessions are easier to start when the work is visible, bounded, and specific. This mock workflow helps reduce task switching.',
                icon: 'track_changes',
                accentColor: '#27764f',
                duration: '25 min',
                level: 'Easy',
                metricLabel: 'Task',
                metricValue: 'One',
                tags: ['Focus', 'Planning', 'Study'],
                highlights: ['Single task', 'Phone away', 'Timer set', 'Short review'],
                steps: ['Write one concrete task.', 'Set a 25-minute timer.', 'Review progress for two minutes.'],
            },
            {
                id: 'connection-check',
                title: 'Connection Check-In',
                kind: 'Mind practice',
                category: 'Connection',
                summary: 'A low-pressure way to maintain social support during busy weeks.',
                detail: 'Small check-ins protect connection without needing a long conversation. They are especially useful when stress creates withdrawal.',
                icon: 'groups',
                accentColor: '#9d6a18',
                duration: '5 min',
                level: 'Easy',
                metricLabel: 'Message',
                metricValue: '1',
                tags: ['Support', 'Social', 'Routine'],
                highlights: ['Choose one person', 'Send a simple message', 'Suggest a short walk', 'Avoid overthinking'],
                steps: ['Pick someone safe and supportive.', 'Send a brief honest message.', 'Schedule a small catch-up if helpful.'],
            },
            {
                id: 'evening-shutdown',
                title: 'Evening Shutdown Ritual',
                kind: 'Mind practice',
                category: 'Recovery',
                summary: 'A routine for closing the study day and lowering mental load before sleep.',
                detail: 'A shutdown ritual helps the brain stop rehearsing unfinished work. It works best when it is brief and repeated consistently.',
                icon: 'nightlight',
                accentColor: '#6a5aa8',
                duration: '12 min',
                level: 'Easy',
                metricLabel: 'List',
                metricValue: 'Tomorrow',
                tags: ['Recovery', 'Sleep', 'Routine'],
                highlights: ['Write tomorrow list', 'Clear desk', 'Dim lights', 'Low-stimulation activity'],
                steps: ['Write the next three priorities.', 'Put materials away.', 'Do one quiet activity before bed.'],
            },
        ],
    },
};
